### ISSUE TITLE
All Backend APIs for techmart

### ISSUE THREAD

**Issue by Amidsts** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#51]
## Summary

*Here is the complete list of all the APIs needed for the project*
**PS: more APIs will be added here with time**

## Technology
  -  nodeJS
  -  MongoDB
  -  ExpressJS
  -  Cloudinary

##  TASKS
-Admin
  - [ ] superAdmin have access to all
  - [ ]   Super admin can invite admin by email

-User Authentication
  - [x] Create an account
  - [ ] Enter verification code sent to email and redirect to kyc form
  - [ ] Kyc form
  - [ ] Verify phone number ( by sending code to the number as sms)
  - [x] Login (or sign in with google or facebook)
  - [ ] Forgot password
  - [ ] Enter email address ( for reset password link, and send link to mail)
  - [ ] Reset password by entering new password and confirm password

-Products
  - [x] Get all products available for sale
  - [x] User Upload/create product
  - [x] User edit/update product
  - [x] User delete product
  - [x] Get product

-message
  - [x] Users can message(DM) each other and also the admin

-Profile
  - [x] Delete account
  - [x]   Change password while logged in
  - [x]   Edit profile details (name, profile picture, account details)

-whishlist
  - [ ] Add to wishlist/cart

-Category
  - [x] Create category
  - [x] Delete category

## Contributing
  - if you want to work on any of these tasks, create a sub issue for the task 
  - Each sub issue should have a reference to this issue (i.e main issue) with `#51`
  -  each sub issue must contain not more than one task
  - each Api you created must be docummented on postman (https://app.getpostman.com/join-team?invite_code=830ec3589bcbcf63ec3fd1a500e7f27e) , before your PR can be merge

## Before you work on any of the tasks,
  - check if it is not assigned to any contributors
  - check if it has not been ticked (i.e worked on)

**NOTE:**  wait till an issue is assigned to you before you start working on it

**ISSUE LL BE UNASSIGNED, IF YOU FAIL TO SUBMIT A PR WITHIN `10 DAYS` AFTER THE ISSUE HAS BEEN CREATED BY YOU**

**Comment by Ayo-Awe** [comment]
The link for the postman documentation is expired or invalid

**Comment by MarsIncarnate** [comment]
Hello @dabsclement could I get added to the backend repo as well? I've already made contributions on the frontend but I'll love to contribute on the backend too.

**Comment by Amidsts** [comment]
Pls guys, if we have contributed before, let's try to have the APIs documented. Before we create new issues. 

  Concerning the  postman link, I will try to reach out to @ @dabsclement
